[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]] # Integrates GNU GLOBAL source code tag system with VIM.
repo = 'vim-scripts/gtags.vim'

[[plugins]] # Integrated reference viewer.
repo = 'thinca/vim-ref'

[[plugins]] # Realtime preview by Vim. (Markdown, reStructuredText, textile)
repo = 'kannokanno/previm'

[[plugins]] # A light and configurable statusline/tabline for Vim
repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {
    \   'colorscheme': 'wombat'
    \}
'''

[[plugins]] # Highlights trailing whitespace in red and provides :FixWhitespace to fix it.
repo = 'bronson/vim-trailing-whitespace'

[[plugins]] # Zeal for Vim
repo = 'KabbAmine/zeavim.vim'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]] # A vim plugin to display the indention levels with thin vertical lines
repo = 'Yggdroot/indentLine'

[[plugins]] # surround.vim: quoting/parenthesizing made simple
repo = 'tpope/vim-surround'

[[plugins]] # unimpaired.vim: pairs of handy bracket mappings
repo = 'tpope/vim-unimpaired'

[[plugins]] # repeat.vim: enable repeating supported plugin maps with .
repo = 'tpope/vim-repeat'

[[plugins]] # easy to use, file-type sensible comments for Vim. It can handle embedded syntax.
repo = 'tomtom/tcomment_vim'

[[plugins]] # easy to use, file-type sensible comments for Vim. It can handle embedded syntax.
repo = 'tomtom/tcomment_vim'

[[plugins]] # incsearch.vim incrementally highlights ALL pattern matches unlike default 'incsearch'
repo = 'haya14busa/incsearch.vim'
hook_add = '''
    " Replace default search commands
    map /  <Plug>(incsearch-forward)
    map ?  <Plug>(incsearch-backward)

    " One that does not move the cursor
    map g/ <Plug>(incsearch-stay)

    " Turn on hlsearch only during searching
    " :h g:incsearch#auto_nohlsearch
    let g:incsearch#auto_nohlsearch = 1
    map n  <Plug>(incsearch-nohl-n)
    map N  <Plug>(incsearch-nohl-N)
    map *  <Plug>(incsearch-nohl-*)
    map #  <Plug>(incsearch-nohl-#)
    map g* <Plug>(incsearch-nohl-g*)
    map g# <Plug>(incsearch-nohl-g#)
'''

#==================================================
# Colors
#==================================================
[[plugins]] # hybrid
repo = 'w0ng/vim-hybrid'

[[plugins]] # solarized
repo = 'altercation/vim-colors-solarized'

[[plugins]] # dracula
repo = 'dracula/vim'

[[plugins]] # molokai
repo = 'tomasr/molokai'

